Repository arshadcodes/AgencyWebsite, pull requests merged in 2024-10, with the labels that each got.

#7 Added Dark Mode
  src/App.jsx
  src/components/DarkModeToggle.jsx
  src/components/Navbar.jsx
  src/components/footer.jsx
  src/components/how things work.jsx
  src/components/main.jsx
  src/components/our work.jsx
  tailwind.config.js
Labels: hactoberfest, hacktoberfest-ready

#14 Added favicon after creating a new one to fit icon size for Hacktoberfest
  index.html
  public/rocket_favicon1.png
  public/vecteezy_rocket-icon-spaceship-launch-startup-icon-set_.jpg
Labels: hactoberfest, hacktoberfest-ready, hacktoberfest-accepted

#31 An enhanced hover effect for navbar items, such as "Services," "Process," and others. #28
  src/components/DarkModeToggle.jsx
  src/components/Navbar.jsx
  src/components/Style/Navbar.css
  src/index.css
Labels: hactoberfest, hacktoberfest-accepted

#36 Feature/responsive footer
  src/components/footer.jsx
Labels: hactoberfest, hacktoberfest-accepted

#47 animated icons
  package-lock.json
  package.json
  src/components/how things work.jsx
  src/components/our work.jsx
Labels: hactoberfest, hacktoberfest-ready, hacktoberfest-accepted

#56 bug fixes
  package-lock.json
  src/components/how things work.jsx
Labels: hactoberfest, hacktoberfest-ready, hacktoberfest-accepted

#64 Docs : Added contributor section to README.md
  README.md
Labels: hactoberfest, hacktoberfest-ready, hacktoberfest-accepted

#68 feat: send mail
  src/components/Work.jsx
  src/components/footer.jsx
  src/components/our work.jsx
Labels: hactoberfest, hacktoberfest-ready, hacktoberfest-accepted

#72 Rename footer.jsx to Footer.jsx
  src/components/Footer.jsx
Labels: hactoberfest, hacktoberfest-ready, hacktoberfest-accepted

#57 Adding Scroll-Driven Animation
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/components/HowThingsWork.jsx
  src/components/Work.jsx
  src/components/anim/how-things-work.css
  src/components/anim/main.css
  src/components/anim/our-work.css
  src/components/how things work.jsx
  src/components/main.jsx
  src/components/our work.jsx
Labels: hactoberfest, hacktoberfest-ready, hacktoberfest-accepted
